version: '3'

services:

  payload:
    image: node:18-alpine
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
      - ./media:/home/node/app/media
      - ./documents:/home/node/app/documents
    working_dir: /home/node/app/
    command: sh -c "npm ci --only=production && npm run build && npm run serve"
    depends_on:
      - mongo
    env_file:
      - .env
    environment:
      MONGODB_URI: mongodb://mongo:27017/payload
      PORT: 3000
      NODE_ENV: production
      MEDIA_DIR: /home/node/app/media
      DOCUMENTS_DIR: /home/node/app/documents
      PAYLOAD_PUBLIC_SERVER_URL: https://cms.lukas-taido.com

  mongo:
    image: mongo:latest
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db
    logging:
      driver: none

volumes:
  data:
  node_modules:
